version: '3'

services:
  
  pwn-babypwn:
    build:
      context: ./pwn/BabyPwn
    container_name: pwn-babypwn
    ports:
      - "1340:9999"
  
  pwn-deadbeef:
    build:
      context: ./pwn/deadbeef
    container_name: pwn-deadbeef
    ports:
      - "1341:9999"
  
  pwn-return-time:
    build:
      context: ./pwn/Return Time
    container_name: pwn-return-time
    ports:
      - "1342:9999"
  
  web-robots-madness:
    build:
      context: ./web/Robots madness
    container_name: web-robots-madness
    ports:
      - "1343:5000"
  
  web-sq-what:
    build:
      context: ./web/SQ What?
    container_name: web-sq-what
    ports:
      - "1344:5000"

  ppc-robotproof:
    build:
      context: ./ppc/RobotProof
    container_name: ppc-robotproof
    ports:
      - "1345:9999"
    
  tuto-web-tasks:
    build:
      context: ./tuto/Web Tasks
    container_name: tuto-web-tasks
    ports:
      - "1346:5000"
  
  tuto-net-cat:
    build:
      context: ./tuto/net... cat?
    container_name: tuto-net-cat
    ports:
      - "1347:9999"
    
  ppc-pipe-maze:
    build:
      context: ./ppc/Pipe Maze
    container_name: ppc-pipe-maze
    ports:
      - "1348:5000"

  ppc-pipe-maze-2:
    build:
      context: ./ppc/Pipe Maze 2
    container_name: ppc-pipe-maze-2
    ports:
      - "1349:5000"
    
  
